### ISSUE TITLE
Observed issues with the schema

### ISSUE THREAD

**Issue by spgennard** [OlegKunitsyn/cobolget#2]
- package name is should allow uppercase & _, as well as common valid filename symbols (understand path sep's not being included)
 - package name, would be nice to have i8n support
 - "List of authors or contributors" has min size of 4 (would 2 better)? id's could be used
 -

**Comment by OlegKunitsyn** [comment]
- no
- no
- Li Wu, for instance. Please use pseudonym

**Comment by spgennard** [comment]
I am not unsure, why you would want to prevent having a more flexible name, don't you even want to use an umlaut or two in your package name?
