### ISSUE TITLE
[Off-topic]: Hey, we wanted to contact you about GCBLUnit and Exercism

### ISSUE THREAD

**Issue by KTSnowy** [OlegKunitsyn/cobolget#9]
Hey @OlegKunitsyn, we're working on a new [standard COBOL track](https://github.com/exercism/cobol) on Exercism, and we'll be needing a COBOL unit test framework for the exercises, we've been having trouble with our current COBOL testing framework. @axtens mentioned that it might be worthwhile reaching out to you in case you'd wants to get involved with the project.

I'm sorry for opening an issue on this repo, I couldn't open an issue on the [GCBLUnit repo](https://github.com/OlegKunitsyn/gcblunit) and didn't know how to contact you outside of GitHub.

**Comment by OlegKunitsyn** [comment]
Apparently I disabled the Issues. Enabled now.
You may find GCBLUnit articles on
- https://medium.com/swlh/modern-cobol-package-tutorial-96d57bc7e23a
- https://medium.com/swlh/modern-cobol-microservice-tutorial-7d7d738f0b00
